<div class="alert alert-block alert-success">

#### 1. What is Numpy
Why are Numpy arrays faster than regular Python lists?

Numpy does not perform type checking while iterating through objects.

Numpy uses fixed types.

Numpy uses contiguous memory.

##### All the Above

<div class="alert alert-block alert-success">

#### 2. Basics of Nympy
What will the following code print?

In [1]:
import numpy as np

b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


<div class="alert alert-block alert-success">

#### 3. Accessing and Chaning Elements, Rows, Columns
What code would change the values in the 3rd column of both of the following Numpy arrays to 20?

In [3]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

a[:, 2] = 20
a

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])

<div class="alert alert-block alert-success">

#### 4. Initializing Different Arrays
What will the following code print?

In [4]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


<div class="alert alert-block alert-success">

#### 5. Initialize Array Problem
What is another way to produce the following array?

    [[0. 0. 0. 0. 0. 0. 0.]    
    [0. 1. 1. 1. 1. 1. 0.]    
    [0. 1. 1. 1. 1. 1. 0.]    
    [0. 1. 1. 5. 1. 1. 0.]    
    [0. 1. 1. 1. 1. 1. 0.]    
    [0. 1. 1. 1. 1. 1. 0.]    
    [0. 0. 0. 0. 0. 0. 0.]]

In [ ]:
output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z

output

<div class="alert alert-block alert-success">

#### 6. Copying Arrays Warning
What is the value of a after running the following code?

In [9]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
b

array([ 1,  2, 20,  4,  5])

<div class="alert alert-block alert-success">

#### 7. Mathematics
What is the value of b after running the following code?

In [10]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
b

15

<div class="alert alert-block alert-success">

#### 8. Reorganizing Arrays
What code would produce the following array?

    [[1. 1.]
    [1. 1.]
    [1. 1.]
    [1. 1.]]

In [ ]:
a = np.ones((2, 4))
b = a.reshape((4, 2))
b

<div class="alert alert-block alert-success">

#### 9. Loading Datadn Advanced Indexing
Given a file named data.txt with these contents:

    29,97,32,100,45
    15,88,5,75,22

What code would produce the following array?

    [29. 32. 45. 15.  5. 22.]

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
output = filedata[filedata < 50]

output